### ISSUE TITLE
create kubernete cluster - broken link

### ISSUE THREAD

**Issue by diegodalmolin** [aws-samples/aws-workshop-for-kubernetes#376]
https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/02-path-working-with-clusters/202-service-mesh#create-kubernetes-cluster
link is broken

**Comment by geremyCohen** [comment]
Will use the same text as this PR after its finalized: https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/499

**Comment by geremyCohen** [comment]
@diegodalmolin thanks for the contribution! Can you specify the url of the page this broken link appears on?

**Comment by geremyCohen** [comment]
Replace with:

In order to perform exercises in this chapter, you'll need to deploy configurations to an EKS cluster.  To create an EKS cluster, use the link:../../01-path-basics/102-your-first-cluster#create-a-kubernetes-cluster-with-eks[AWS CLI] (recommended), or alternatively, link:../../01-path-basics/102-your-first-cluster#alternative-create-a-kubernetes-cluster-with-kops[kops].
