### ISSUE TITLE
Module 401: curl command is overly complex

### ISSUE THREAD

**Issue by rddefauw** [aws-samples/aws-workshop-for-kubernetes#480]
In this module, the curl commands try to use the public DNS for the Cloud9 instance.  However, some firewalls block the ports used in the example.  It is easier to use `localhost:8080` in the curl command.

**Comment by buzzsurfr** [comment]
This was reviewed in #364 and fixed in #392 to use this format below, since this the default FQDN projected inside of the Cloud9 IDE.

https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/87b8d5f20b9f79e80f8d7b9a4a75a6ed4a2ffa95/04-path-security-and-networking/401-configmaps-and-secrets/readme.adoc#L280
